language: node_js
dist: trusty
sudo: required
node_js: node

env:
  - LOGGER_LEVEL='INFO'

services:
  - docker

before_install:
  - $TRAVIS_BUILD_DIR/tools/travis/install-openwhisk.sh
  - export OPENWHISK_HOME=$TRAVIS_BUILD_DIR/openwhisk
# - $TRAVIS_BUILD_DIR/bin/bxsetup.sh

install:
  - cd $TRAVIS_BUILD_DIR && npm install && npm link
  - cd $TRAVIS_BUILD_DIR/plugins/actions/combinator && npm install && npm link openwhisk-deploy
  - cd $TRAVIS_BUILD_DIR/plugins/actions/web && npm install && npm link openwhisk-deploy  
 
script:
  - cd $TRAVIS_BUILD_DIR &&  NODE_TLS_REJECT_UNAUTHORIZED=0 npm test
  - cd $TRAVIS_BUILD_DIR/plugins/actions/combinator && NODE_TLS_REJECT_UNAUTHORIZED=0 npm test
  - cd $TRAVIS_BUILD_DIR/plugins/actions/web && NODE_TLS_REJECT_UNAUTHORIZED=0 npm test
  