language: node_js
dist: trusty
sudo: required
node_js: node

env:
  global:
    - LOGGER_LEVEL='INFO'
  matrix:
    - LOCALWSK=true
    - LOCALWSK=false

services:
  - docker

install:
  - cd $TRAVIS_BUILD_DIR && npm install
  - if [ "$LOCALWSK" = "true" ]; then $TRAVIS_BUILD_DIR/tools/travis/install-openwhisk.sh ; fi
  - if [ "$LOCALWSK" = "false" ]; then $TRAVIS_BUILD_DIR/tools/travis/bxsetup.sh ; fi
  - export OPENWHISK_HOME=$TRAVIS_BUILD_DIR/openwhisk

script:
  - cd $TRAVIS_BUILD_DIR && NODE_TLS_REJECT_UNAUTHORIZED=0 npm test
  - cd $TRAVIS_BUILD_DIR

after_success: npm run coverage