language: node_js
dist: trusty
sudo: required
node_js: node

env:
  - LOGGER_LEVEL='INFO'

services:
  - docker

before_install:
  - $TRAVIS_BUILD_DIR/tools/travis/install-openwhisk.sh
  - $TRAVIS_BUILD_DIR/bin/bxsetup.sh

install:
  - cd $TRAVIS_BUILD_DIR && npm install
  - cd $TRAVIS_BUILD_DIR/plugins/actions/combinator && npm install
 
script:
  - $TRAVIS_BUILD_DIR/bin/runtests.sh
