language: node_js
dist: trusty
sudo: true
node_js: node

before_install:
  - cd $TRAVIS_BUILD_DIR/libs/builder && npm install
  - cd $TRAVIS_BUILD_DIR/libs/deployer && npm install

script:
  - cd $TRAVIS_BUILD_DIR/libs/builder && npm test
  - cd $TRAVIS_BUILD_DIR/libs/deployer && npm test

